# apiVersion: v1
# kind: Secret
# type: kubernetes.io/basic-auth
# metadata:
#   name: gitlab-token
#   annotations:
#     tekton.dev/git-0: https://gitlab.com
# stringData:
#   username: Dundek
#   password: zCy_Yx1EudG3GbjTCurc
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: apaasctl-credentials
# data:
#   password: UkV1ZlAzNlRX
#   username: bWRAZ21haWwuY29t
# ---
# apiVersion: v1
# kind: Secret
# type: kubernetes.io/dockerconfigjson
# metadata:
#   name: apaas-registry-secret
# data:
#   .dockerconfigjson: eyJhdXRocyI6eyJhcGFhcy1yZWdpc3RyeS5tbCI6eyJ1c2VybmFtZSI6Im1kQGdtYWlsLmNvbSIsInBhc3N3b3JkIjoiUkV1ZlAzNlRXIiwiZW1haWwiOiJtZEBnbWFpbC5jb20iLCJhdXRoIjoiYldSQVoyMWhhV3d1WTI5dE9sSkZkV1pRTXpaVVZ3PT0ifX19
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gitlab-token
spec:
  encryptedData:
    password: AgDFyAWgm8K9KgpclQ9SqeVYhHcT7Cs08kGyTcCBE62h8ZHaAHZK50XIf/jApUkVjJT2QEegl0XU4CAqkTBMyvqiFpNNL7ZewElfoEGij0aFYeKdlXkS5h3xUVpZzGk4ILYgqpPNG9Y77GOJu4Q+Eh5s1CEVKu9tdYeWQQ5Xhsl7w/Wbanlu+/KngsYVhl+mkurg1Rna/vo6nPXjX19OXlRffIROBQbHL817dW4gH+vDlZbkjl70/mHUIQ0u/BZhQ3Hc92wyfBoCAJwMDj/4yOTsE1bqLJObwCa89OJkkzX8AkgVMPZfDkvsMPoOg5TZ1B/ULXxvWhxE0QhYgncvOT3RD0qFxEKeqhT9qvA+eVa3mQD6N4UXuvI2f/iHzFdTdlkyDJwW+0/Hca8fxqFoZYcxdMrl52HweDk3rKDbMK2z77xq9KP3oP0++NAU/9AXxKYqdDbxT9lUZGjofQ4jCz2tCH6ivw/7Cbef0EjSPiQF5BN3fnfbpltHNzv2Iy+R32yqS1/h1NO7cWIEqolGQbNorjPGzxiqdnFDunKyI5BN2S5FGa9bZ3MQeRgQ4rgh9EMR8LthxUfZlB8an5LyMt3nuWUv8eEgYnOCFJqoT0InxI8eDrM3Y48tuKwjSTHEHe4WFuK2qgVoVEadY31F5hLdTFhMkroBdHzyW8P6nF4qUuNfMvrAwwfdJLXvSrXj84Low7gd0e7sxtVnClB7RHtVciOvQw==
    username: AgDRQhod3tbgejYlfl+7JfNKP6+8hKXTgmFHi7rA2jIYdJTbDexZR7D+oPwRIBTzNu7guH60qBIzVIJE90TwjNeV9rEknKmjdWwmhYUJ/ox5/fPpIHgo+CTOlVwUxzEqUIoTjZHNEeeomvAvR/W6uYsnsgCeF/zIeFxOeb2oRETbi1HerKaGby12/VI18LyjUl1J2pICr0T0WCEwdRSik258jLXVzzoEXJU8x7P+/7R6monE9an6Pk6+nCudP2VcnGl/Xqi45cit2CAindWWAKwE05faARWRoYlUJJJVhgc6cCp/ONy+TYu1sSMIaDG5+SLtFyHputHKfjQh3qpjGT2Jh0klHN2/ePuwTewo4Y56DC+xC/vGNF/ExV6dnt9dMSfYVSiEvaFpur+HE8KF7dmRkxxOSm/yjt3HkhFJsyMXyvBS3PSi6hnEzESIIBZlQ0oOQo36PX7fMSLnLrmFtMyYk+vsBXCofBtI9JwEA1hGAG298JvfIonXXVocZOSkKYy0fa0gSEE+96+/M2n32AM7w6UEPfHcKYLAOJrQ3D5QrXiMKS4an7ORN26FmT6O+LEqYLbK3tATVLhM5Euuvaf8DYKxYLHdzwQJYI3gbI4ZsjfSwaUrnum6uyW9WlMBjf1hCGZX4R+FyPBzrCewd1enS4JFanlBJxirBTtzflCFu4hVXub0QmxELnOYPVdWkrk7fPcuFWg=
  template:
    metadata:
      annotations:
        tekton.dev/git-0: https://gitlab.com
      name: gitlab-token
      namespace: dev
    type: kubernetes.io/basic-auth

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apaasctl-credentials
spec:
  encryptedData:
    password: AgABnsNyZdPuD9fE0+RzndwB4iFrkeWtW9yEx2cDlF1lnH7pJuTRtYWRsBS3tLVW5AIkErrQlg0HDxLpinUhXYEFf+x7JRp107OmcbBBxllRe+TA2QNaTzmI9JuHPdL9K9dssdH0ElxAmNxLRpRMNLliCCxQbpegjcnEPJgMlHn01fghBMBw5hCuHN2W4/cM4DSD77GP8BwZEFLsaSZqykkbFCn6TUbw+1vK5eZXvj9WWb80t0TN0nmiU1Gv5rJCAWeyz6++zGlD5CIJkQGE/MR39D1JCWQHBeb2kYfB3kKuBn4MZszZ77YAKIfjoraxDmPpnkX8wTTyq7aogM4H7AIhpvN9zy9qivN3BmwIJPC66Avr5Z9bi5lwk3d+VghJRoA/zGooVw9ALzRGdSN79iO/EySmvL9tLGs42NF3j5mgZ8zfbp/Wqe7sbXZSEX0PdvV967dSBXiGnAYI/8XJt8+kMpfFlG245LXggqK1+ore4ClneWz69ptx+7w93RZl5nYwACZzDNPh53B73KNEbiFEXbPbJdS7vBx5M+99MUtjuuULxxv7HPOhDmEHT2nm9nLsNENYE8ILefIdb3G8wqtDhcBS1MJtxI4Q9XgplDALCSGKrdEoX1BB1vIy7PWvqbtwI3rbW6xm93BXM6FtFKaqi6WJEJNyHmodootMS8GZBjr5LlcPbsefvBTg9zMvfKyCZT/x+7ecv88=
    username: AgBn879Vuut1TJZJ/cAPZYkfL1tHcDzZ2wLfgifx571g0wL5I0yCqqRCJUerQ5XSBey668cVauJGz0KwDRYNHB0/GUL6QaNdAQGE2nsXd+r+ABO6ItrpoNUlvOYDZWhxt/Z75Xd3zKXqk/EuGppuiDX4IcDsAkf5t62RBdNNq5nGH0vEuO8JkK96dj7uRRRMzX9Q+qh9PiDvNt7yKF9wmaHQuTv3+vH5HJjmgYf+2Zaj32UwDvDiOFk1A2DUan9y1D+OsAtIJK2uONHWpwmmtd8CU1kYC5vW+PbHO9zxcvqMlVkO6pAP1GsUuYXic0IpnY01MFiZZ4DEJw7cNwYwv+n5OfV20aZbab4s1h8fC0PRCU4Y1AbBReosmz0CH5ZDok4GxeYm7NQl8k6agTnM7h47C0+CK4GBEJCYfOlbj8YvDSL6XpmbJQTyvuERfz5kDJO4n9MOolrE1HCPBGN62xBSbShzWTpZ0LN3DL5/z3sbChz0zfiGCy9L/2/lEB6pBhc+xDC2Z9BSq1dXoS5kF8KO4zvJJ4nf3ubYAc1QmUdXe48zV2tu7reY1he5i+ez7+TwO51DkuytxoLZGQ8tcJx/d9BCuLWfFXYAdVb/ss0Gn526jF2HG66HCF6oBZHxO+tfajItyWkKJnizo3vqX+d8f+egfRVtEZCmsBgd6R6xYTUMMWAXJqgjl6/sdVfGpbpZUxrBsIT5JGR91TA=
  template:
    metadata:
      name: apaasctl-credentials
      namespace: dev

---

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: apaas-registry-secret
spec:
  encryptedData:
    .dockerconfigjson: AgA1Fnabdod8vjcIUK5WRDxJgnwlBXsyLbqQgf/ShjitZVvcrMIyiTuzQJclhGF30WIuidjIzqhvK7bjaRTsiV0wH3HvKG828kvYI80RzRb0Kyg9ve57cJzQ70Vmnlnz2oYqmOTOUZYHPfE/fQjA78mMgTY+GLutR0hJmXpysWtUUFnIM4a1VXzMdpxaY8JrPevghVyTBQESwgeLWYctYtlC3IIBoxRtofCSJYocaNkltwK7XgTf2ilP8g+yqKVJwk2smCdoo12+AJ2pBE7VMSQTq7nOQHF3LMsp1k6ozgGeuNhkifH/ChTuOD5BtvknKAndkUyRJLusuneocJTyRpmmNDFY1uzzUD8zl7Br02n6/8OCDJU8yZWpBur7YF5k1ikYMxGeji/NP8GYuTQ9P+PcLxcg9nEe2rzMLwdbdi/+jSVlQPtxJuFqVuymkC7yK/cJ9Gh2zztp86/UC1CHvmMJS6bKD/6CJ47NQgKXR3J3mHTIJFLc0Yqct50CS5tFYHmCN9VF2la+zi4IAu9NXuPpMMFc5ycq2CuSVSjye3GoMk3wGebro1fKDK55UpNG8iPJQpJuHiLeEEzqsoCqQqBT159V6zaXLgFVN/8Ao3U8Mvx+KRIYiJFa5qrKNP2rQdmwTJUPvBUiD7gK3Fk6JaJxC/YAtKkWXqColkBcTCkkjYQjtWvLFLsqQ3rh9TOQuZC3aExdHqwgtK/NXHnV0CQs1Zx4dFUStoCn9GiEcpmwlH++Zh82B+CXpdmhJb92hVwfzhYA0D4Piwqfiphmdd4AmbWSQlF7n06LiDpj0kKi12fXRS7iUCnRZ2XolYupT6vwjwrGFEAT4hXsHHhCTRGRYFSJFvWXASND46V/YxpJbjKaeS7eJpt9FY73reIsG1IQAys=
  template:
    metadata:
      annotations:
        tekton.dev/docker-0: https://apaas-registry.ml
      name: apaas-registry-secret
      namespace: dev
    type: kubernetes.io/dockerconfigjson

---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipeline-service-account
secrets:
  - name: gitlab-token
  - name: apaas-registry-secret
  - name: apaasctl-credentials